graph TD
    org_uacalc_alg_Algebra["Algebra"]
    org_uacalc_alg_AlgebraFromMinimalSets["AlgebraFromMinimalSets"]
    org_uacalc_alg_AlgebraWithGeneratingVector["AlgebraWithGeneratingVector"]
    org_uacalc_alg_BasicAlgebra["BasicAlgebra"]
    org_uacalc_alg_BigProductAlgebra["BigProductAlgebra"]
    org_uacalc_alg_Closer["Closer"]
    org_uacalc_alg_FreeAlgebra["FreeAlgebra"]
    org_uacalc_alg_GeneralAlgebra["GeneralAlgebra"]
    org_uacalc_alg_Malcev["Malcev"]
    org_uacalc_alg_MaltsevDecompositionIterator["MaltsevDecompositionIterator"]
    org_uacalc_alg_MatrixPowerAlgebra["MatrixPowerAlgebra"]
    org_uacalc_alg_PolinLikeAlgebra["PolinLikeAlgebra"]
    org_uacalc_alg_PowerAlgebra["PowerAlgebra"]
    org_uacalc_alg_ProductAlgebra["ProductAlgebra"]
    org_uacalc_alg_QuotientAlgebra["QuotientAlgebra"]
    org_uacalc_alg_ReductAlgebra["ReductAlgebra"]
    org_uacalc_alg_SmallAlgebra["SmallAlgebra"]
    org_uacalc_alg_SubProductAlgebra["SubProductAlgebra"]
    org_uacalc_alg_Subalgebra["Subalgebra"]
    org_uacalc_alg_UnaryTermsMonoid["UnaryTermsMonoid"]
    org_uacalc_alg_conlat_BasicBinaryRelation["BasicBinaryRelation"]
    org_uacalc_alg_conlat_BasicPartition["BasicPartition"]
    org_uacalc_alg_conlat_BinaryRelation["BinaryRelation"]
    org_uacalc_alg_conlat_CentralityData["CentralityData"]
    org_uacalc_alg_conlat_CongruenceLattice["CongruenceLattice"]
    org_uacalc_alg_conlat_Partition["Partition"]
    org_uacalc_alg_op_AbstractIntOperation["AbstractIntOperation"]
    org_uacalc_alg_op_Operation["Operation"]
    org_uacalc_alg_op_OperationSymbol["OperationSymbol"]
    org_uacalc_alg_op_OperationWithDefaultValue["OperationWithDefaultValue"]
    org_uacalc_alg_op_Operations["Operations"]
    org_uacalc_alg_op_TermOperation["TermOperation"]
    org_uacalc_alg_op_TermOperationImp["TermOperationImp"]
    org_uacalc_alg_parallel_SingleClose["SingleClose"]
    org_uacalc_alg_sublat_BasicSet["BasicSet"]
    org_uacalc_alg_sublat_SubalgebraLattice["SubalgebraLattice"]
    org_uacalc_element_Element["Element"]
    org_uacalc_element_SubProductElement["SubProductElement"]
    org_uacalc_example_FiniteField["FiniteField"]
    org_uacalc_fplat_PartiallyDefinedLattice["PartiallyDefinedLattice"]
    org_uacalc_group_PermutationGroup["PermutationGroup"]
    org_uacalc_io_BadAlgebraFileException["BadAlgebraFileException"]
    org_uacalc_io_ExtFileFilter["ExtFileFilter"]
    org_uacalc_lat_BasicLattice["BasicLattice"]
    org_uacalc_lat_Lattice["Lattice"]
    org_uacalc_lat_Order["Order"]
    org_uacalc_lat_OrderedSets["OrderedSets"]
    org_uacalc_lat_SmallLattice["SmallLattice"]
    org_uacalc_nbui_AlgebraPreviewer["AlgebraPreviewer"]
    org_uacalc_nbui_ComputationsController["ComputationsController"]
    org_uacalc_nbui_LatDrawer["LatDrawer"]
    org_uacalc_nbui_MainController["MainController"]
    org_uacalc_nbui_PopupListener["PopupListener"]
    org_uacalc_nbui_UACalc["UACalc"]
    org_uacalc_nbui_UACalculator2["UACalculator2"]
    org_uacalc_nbui_UACalculatorUI["UACalculatorUI"]
    org_uacalc_terms_NonVariableTerm["NonVariableTerm"]
    org_uacalc_terms_Term["Term"]
    org_uacalc_terms_Variable["Variable"]
    org_uacalc_terms_VariableImp["VariableImp"]
    org_uacalc_ui_AlgebraEditor["AlgebraEditor"]
    org_uacalc_ui_AlgebraTableInputPanel["AlgebraTableInputPanel"]
    org_uacalc_ui_ComputationsPanel["ComputationsPanel"]
    org_uacalc_ui_LatDrawPanel["LatDrawPanel"]
    org_uacalc_ui_MonitorPanel["MonitorPanel"]
    org_uacalc_ui_NewAlgebraDialog["NewAlgebraDialog"]
    org_uacalc_ui_PropertiesPanel["PropertiesPanel"]
    org_uacalc_ui_Tabs["Tabs"]
    org_uacalc_ui_UACalculator["UACalculator"]
    org_uacalc_ui_table_AlgebraTableModel["AlgebraTableModel"]
    org_uacalc_ui_table_AlgebraTablePanel["AlgebraTablePanel"]
    org_uacalc_ui_table_ElemKeyTableModel["ElemKeyTableModel"]
    org_uacalc_ui_table_IntegerEditor["IntegerEditor"]
    org_uacalc_ui_table_OperationInputTable["OperationInputTable"]
    org_uacalc_ui_table_OperationTableModel["OperationTableModel"]
    org_uacalc_ui_table_TaskTableModel["TaskTableModel"]
    org_uacalc_ui_table_TermTableModel["TermTableModel"]
    org_uacalc_ui_table_TermTablePanel["TermTablePanel"]
    org_uacalc_ui_tm_GuiExecutor["GuiExecutor"]
    org_uacalc_ui_util_GUIAlgebraList["GUIAlgebraList"]
    org_uacalc_util_ArrayIncrementor["ArrayIncrementor"]
    org_uacalc_util_IntArray["IntArray"]
    org_uacalc_util_SimpleList["SimpleList"]
    org_uacalc_util_virtuallist_LongList["LongList"]
    org_uacalc_util_virtuallist_TupleWithMin["TupleWithMin"]
    org_uacalc_ui_LatDrawPanel --> org_uacalc_lat_BasicLattice
    org_uacalc_ui_UACalculator --> org_uacalc_ui_table_AlgebraTablePanel
    org_uacalc_ui_UACalculator --> org_uacalc_alg_op_Operation
    org_uacalc_ui_UACalculator --> org_uacalc_ui_MonitorPanel
    org_uacalc_ui_UACalculator --> org_uacalc_alg_op_Operations
    org_uacalc_ui_AlgebraEditor --> org_uacalc_alg_op_Operation
    org_uacalc_ui_AlgebraEditor --> org_uacalc_alg_op_OperationWithDefaultValue
    org_uacalc_ui_AlgebraEditor --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_ui_AlgebraEditor --> org_uacalc_alg_op_Operations
    org_uacalc_lat_BasicLattice --> org_uacalc_alg_op_Operation
    org_uacalc_lat_BasicLattice --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_fplat_PartiallyDefinedLattice --> org_uacalc_lat_Order
    org_uacalc_group_PermutationGroup --> org_uacalc_alg_op_Operation
    org_uacalc_group_PermutationGroup --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_nbui_ComputationsController --> org_uacalc_alg_sublat_BasicSet
    org_uacalc_nbui_MainController --> org_uacalc_alg_op_Operation
    org_uacalc_nbui_MainController --> org_uacalc_alg_op_OperationWithDefaultValue
    org_uacalc_nbui_MainController --> org_uacalc_alg_op_Operations
    org_uacalc_terms_VariableImp --> org_uacalc_alg_op_Operation
    org_uacalc_terms_VariableImp --> org_uacalc_util_SimpleList
    org_uacalc_terms_VariableImp --> org_uacalc_alg_op_TermOperation
    org_uacalc_terms_VariableImp --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_terms_VariableImp --> org_uacalc_alg_op_TermOperationImp
    org_uacalc_terms_Variable --> org_uacalc_util_SimpleList
    org_uacalc_terms_Term --> org_uacalc_alg_op_TermOperation
    org_uacalc_terms_Term --> org_uacalc_alg_op_Operation
    org_uacalc_terms_Term --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_terms_NonVariableTerm --> org_uacalc_alg_op_Operation
    org_uacalc_terms_NonVariableTerm --> org_uacalc_alg_op_TermOperation
    org_uacalc_terms_NonVariableTerm --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_terms_NonVariableTerm --> org_uacalc_alg_op_Operations
    org_uacalc_terms_NonVariableTerm --> org_uacalc_alg_op_TermOperationImp
    org_uacalc_alg_PolinLikeAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_PolinLikeAlgebra --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_alg_FreeAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_FreeAlgebra --> org_uacalc_alg_op_Operations
    org_uacalc_alg_SubProductAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_SubProductAlgebra --> org_uacalc_alg_op_Operations
    org_uacalc_alg_GeneralAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_GeneralAlgebra --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_alg_GeneralAlgebra --> org_uacalc_alg_op_Operations
    org_uacalc_alg_QuotientAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_QuotientAlgebra --> org_uacalc_alg_op_Operations
    org_uacalc_alg_Algebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_Algebra --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_alg_PowerAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_PowerAlgebra --> org_uacalc_alg_sublat_SubalgebraLattice
    org_uacalc_alg_BasicAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_BasicAlgebra --> org_uacalc_alg_op_OperationWithDefaultValue
    org_uacalc_alg_BasicAlgebra --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_alg_BasicAlgebra --> org_uacalc_alg_op_Operations
    org_uacalc_alg_Subalgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_Subalgebra --> org_uacalc_alg_op_Operations
    org_uacalc_alg_Closer --> org_uacalc_alg_op_OperationWithDefaultValue
    org_uacalc_alg_Closer --> org_uacalc_alg_op_Operation
    org_uacalc_alg_Closer --> org_uacalc_alg_parallel_SingleClose
    org_uacalc_alg_Closer --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_alg_Closer --> org_uacalc_alg_op_Operations
    org_uacalc_alg_ReductAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_BigProductAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_BigProductAlgebra --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_alg_BigProductAlgebra --> org_uacalc_alg_op_Operations
    org_uacalc_alg_UnaryTermsMonoid --> org_uacalc_alg_conlat_CongruenceLattice
    org_uacalc_alg_UnaryTermsMonoid --> org_uacalc_alg_sublat_SubalgebraLattice
    org_uacalc_alg_MatrixPowerAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_MatrixPowerAlgebra --> org_uacalc_alg_op_Operations
    org_uacalc_alg_ProductAlgebra --> org_uacalc_alg_op_Operation
    org_uacalc_alg_ProductAlgebra --> org_uacalc_alg_op_Operations
    org_uacalc_alg_SmallAlgebra --> org_uacalc_alg_sublat_SubalgebraLattice
    org_uacalc_alg_SmallAlgebra --> org_uacalc_alg_conlat_CongruenceLattice
    org_uacalc_element_Element --> org_uacalc_alg_Algebra
    org_uacalc_example_FiniteField --> org_uacalc_alg_op_Operation
    org_uacalc_example_FiniteField --> org_uacalc_alg_GeneralAlgebra
    org_uacalc_example_FiniteField --> org_uacalc_alg_SmallAlgebra
    org_uacalc_util_IntArray --> org_uacalc_alg_conlat_Partition
    org_uacalc_ui_table_OperationInputTable --> org_uacalc_ui_UACalculator
    org_uacalc_ui_table_OperationInputTable --> org_uacalc_alg_op_Operation
    org_uacalc_ui_table_OperationInputTable --> org_uacalc_alg_op_OperationWithDefaultValue
    org_uacalc_ui_table_OperationInputTable --> org_uacalc_ui_table_OperationTableModel
    org_uacalc_ui_table_ElemKeyTableModel --> org_uacalc_alg_conlat_Partition
    org_uacalc_ui_table_OperationTableModel --> org_uacalc_ui_UACalculator
    org_uacalc_ui_table_OperationTableModel --> org_uacalc_alg_op_Operation
    org_uacalc_ui_table_OperationTableModel --> org_uacalc_alg_op_OperationWithDefaultValue
    org_uacalc_ui_table_OperationTableModel --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_ui_table_OperationTableModel --> org_uacalc_alg_op_Operations
    org_uacalc_ui_table_OperationTableModel --> org_uacalc_util_ArrayIncrementor
    org_uacalc_ui_table_AlgebraTableModel --> org_uacalc_alg_SmallAlgebra
    org_uacalc_alg_conlat_CongruenceLattice --> org_uacalc_alg_op_Operation
    org_uacalc_alg_conlat_CongruenceLattice --> org_uacalc_alg_op_OperationSymbol
    org_uacalc_alg_op_TermOperationImp --> org_uacalc_alg_SmallAlgebra
    org_uacalc_alg_op_Operations --> org_uacalc_alg_conlat_BasicPartition
    org_uacalc_alg_sublat_BasicSet --> org_uacalc_util_IntArray
    org_uacalc_alg_sublat_BasicSet --> org_uacalc_alg_SmallAlgebra
    org_uacalc_alg_sublat_SubalgebraLattice --> org_uacalc_alg_op_Operation
    org_uacalc_alg_sublat_SubalgebraLattice --> org_uacalc_alg_op_OperationSymbol