<?xml version="1.0"?>
<algebra>
  <quotientAlgebra>
    <cardinality>2</cardinality>
    <superAlgebra>
      <basicAlgebra>
        <algName>C2</algName>
        <desc>The two element group.</desc>
        <cardinality>2</cardinality>
        <operations>
          <op>
            <opSymbol>
              <opName>+</opName>
              <arity>2</arity>
            </opSymbol>
            <opTable>
              <intArray>
                <row r="[0]">0,1</row>
                <row r="[1]">1,0</row>
              </intArray>
            </opTable>
          </op>
        </operations>
      </basicAlgebra>
    </superAlgebra>
    <congruence>
      <partition>
        |0|1|
      </partition>
      <intArray>
        -1,-1
      </intArray>
    </congruence>
  </quotientAlgebra>
</algebra>
