package org.uacalc.example;

import java.io.*;
import java.util.*;
import org.uacalc.alg.*;
import org.uacalc.terms.*;
import org.uacalc.eq.*;
import org.uacalc.io.*;

/**
 * Test version of MembershipTester that uses relative paths.
 * 
 * This version uses paths relative to the project root instead of
 * hardcoded absolute paths.
 */
public class MembershipTesterTest {
  
  static String alg0File = "resources/algebras/n5.ua";
  static String alg1File = "resources/algebras/m3.ua";
  // This should be a generating set of alg1. Make it as small as possible.
  static int[] alg1Generators = new int[] { 1, 2, 3 };
  
  public static void main(String[] args) throws IOException, BadAlgebraFileException {
    SmallAlgebra alg0 = org.uacalc.io.AlgebraIO.readAlgebraFile(alg0File);
    SmallAlgebra alg1 = org.uacalc.io.AlgebraIO.readAlgebraFile(alg1File);
    // The third argument below is a generating set of alg1.
    Equation eq = FreeAlgebra.findEquationOfAnotB(alg0, alg1, alg1Generators);
    System.out.println("eq is\n" + eq);
    if (eq != null) {  // if eq == null, alg1 is in V(alg0), 
                       // or at least the subalgebra generated by the generators is.
      // test that eq fails in alg1 (of course it does).
      Map<Variable, Integer> failure = eq.findFailureMap(alg1);
      System.out.println("failure in alg1\n" + failure);
      // try to find a failure in alg0 (of course there is none).
      failure = eq.findFailureMap(alg0);
      System.out.println("failure in alg0\n" + failure);
    } else {
      System.out.println("eq is null (alg1 is in V(alg0))");
    }
  }
  
}

