# coding: utf-8
#!/usr/bin/env python3
"""
Generate jython_comparison/parity_inventory.yaml from the Java org.uacalc tree,
java_wrapper CLI wrappers, and python/org/uacalc shims.

Usage (from repo root):
  python jython_comparison/scripts/generate_parity_inventory.py
  python jython_comparison/scripts/generate_parity_inventory.py --verify

--verify checks that parity_inventory.yaml exists and matches the output of
``build_inventory`` (ignoring generation timestamp and repo_root), so CI is
not fooled by checkout file mtimes.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Set, Tuple


GENERATOR_VERSION = 1

_RE_META_UTC = re.compile(r"(?m)^[ \t]+generated_at_utc:[^\n]*\n")
_RE_META_REPO_ROOT = re.compile(r"(?m)^([ \t]+)repo_root:[^\n]*\n")


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


# --- YAML subset emitter (no PyYAML dependency) ---


def _yaml_escape_string(s: str) -> str:
    if "\n" in s or "\r" in s:
        raise ValueError("Multiline strings must use | block; not supported inline")
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    if (
        not s
        or s.strip() != s
        or any(c in s for c in ':#[]{},&*!?|>-%')
        or s[0] in ("@", "`")
        or "\t" in s
    ):
        return f'"{escaped}"'
    return s


def _yaml_dump(obj: Any, indent: int = 0) -> List[str]:
    prefix = " " * indent
    lines: List[str] = []

    if obj is None:
        lines.append(f"{prefix}null")
    elif isinstance(obj, bool):
        lines.append(f"{prefix}{'true' if obj else 'false'}")
    elif isinstance(obj, (int, float)):
        lines.append(f"{prefix}{obj}")
    elif isinstance(obj, str):
        lines.append(f"{prefix}{_yaml_escape_string(obj)}")
    elif isinstance(obj, list):
        if not obj:
            lines.append(f"{prefix}[]")
        else:
            for item in obj:
                if isinstance(item, (dict, list)) and item:
                    lines.append(f"{prefix}-")
                    sub = _yaml_dump(item, indent + 2)
                    # first line of sub attaches after "-"
                    if sub:
                        first = sub[0].strip()
                        lines[-1] = f"{prefix}- {first}"
                        lines.extend(sub[1:])
                else:
                    if isinstance(item, str):
                        lines.append(f"{prefix}- {_yaml_escape_string(item)}")
                    elif isinstance(item, bool):
                        lines.append(f"{prefix}- {'true' if item else 'false'}")
                    elif item is None:
                        lines.append(f"{prefix}- null")
                    else:
                        lines.append(f"{prefix}- {item}")
    elif isinstance(obj, dict):
        if not obj:
            lines.append(f"{prefix}{{}}")
        else:
            for k, v in obj.items():
                key = str(k)
                if any(c in key for c in ':#?[]{},&*!|>%'):
                    key = _yaml_escape_string(key)
                if isinstance(v, (dict, list)) and v:
                    lines.append(f"{prefix}{key}:")
                    lines.extend(_yaml_dump(v, indent + 2))
                else:
                    if isinstance(v, str):
                        lines.append(f"{prefix}{key}: {_yaml_escape_string(v)}")
                    elif isinstance(v, bool):
                        lines.append(f"{prefix}{key}: {'true' if v else 'false'}")
                    elif v is None:
                        lines.append(f"{prefix}{key}: null")
                    elif isinstance(v, (int, float)):
                        lines.append(f"{prefix}{key}: {v}")
                    else:
                        sub = _yaml_dump(v, indent + 2)
                        lines.append(f"{prefix}{key}:")
                        lines.extend(sub)
    else:
        raise TypeError(f"Unsupported type for YAML dump: {type(obj)!r}")
    return lines


def format_inventory_yaml(data: Mapping[str, Any], repo: Path) -> str:
    """Full file text as written by ``write_yaml`` (for verification)."""
    lines = _yaml_dump(dict(data))
    try:
        script_rel = Path(__file__).resolve().relative_to(repo).as_posix()
    except ValueError:
        script_rel = Path(__file__).as_posix()
    header = (
        f"# AUTO-GENERATED by {script_rel}\n"
        f"# Generator version: {GENERATOR_VERSION}\n"
        "# Do not edit by hand; run the script to refresh.\n"
    )
    return header + "\n".join(lines) + "\n"


def write_yaml(path: Path, data: Mapping[str, Any], repo: Path) -> None:
    path.write_text(format_inventory_yaml(data, repo), encoding="utf-8")


def _normalize_parity_inventory_text(text: str) -> str:
    """Strip machine-specific meta so two working trees can be compared."""
    text = text.replace("\r\n", "\n")
    text = _RE_META_UTC.sub("", text)
    text = _RE_META_REPO_ROOT.sub(r'\1repo_root: "<normalized>"\n', text)
    return text


# --- Java scanning ---

_PACKAGE_RE = re.compile(r"^\s*package\s+([\w.]+)\s*;", re.MULTILINE)
_PUBLIC_TYPE_RE = re.compile(
    r"^\s*public\s+(?:abstract\s+|final\s+)?(class|interface|enum)\s+(\w+)",
    re.MULTILINE,
)
_IMPORT_ORG_UACALC = re.compile(r"^\s*import\s+(org\.uacalc\.[\w.]+)\s*;")


def _extract_public_methods(java_source: str) -> List[str]:
    """Heuristic public method names (excludes constructors with different rule). Skips obvious non-methods."""
    names: Set[str] = set()
    for line in java_source.splitlines():
        s = line.strip()
        if not s.startswith("public"):
            continue
        if re.search(r"\b(class|interface|enum)\b", s):
            continue
        if "(" not in s or ")" not in s:
            continue
        # Ignore likely field declarations with '='
        if "=" in s and s.index("=") < s.rindex("("):
            continue
        pre = s.split("(", 1)[0]
        m = re.search(r"(\w+)\s*$", pre)
        if not m:
            continue
        name = m.group(1)
        if name in ("if", "for", "while", "switch", "return", "throw", "new", "true", "false", "null"):
            continue
        if name[0].isupper() and "(" in s:
            # could be constructor ClassName( - still a public surface in Jython
            pass
        names.add(name)
    return sorted(names)


def _parse_java_file(path: Path) -> Tuple[str, List[Tuple[str, str]], List[str]]:
    text = path.read_text(encoding="utf-8", errors="replace")
    pkg_m = _PACKAGE_RE.search(text)
    package = pkg_m.group(1) if pkg_m else ""
    types: List[Tuple[str, str]] = []
    for line in text.splitlines():
        m = _PUBLIC_TYPE_RE.match(line)
        if m:
            kind, name = m.group(1), m.group(2)
            types.append((kind, name))
    methods = _extract_public_methods(text)
    return package, types, methods


def _walk_org_uacalc_java(repo: Path) -> List[Path]:
    root = repo / "org" / "uacalc"
    out: List[Path] = []
    for dirpath, _, files in os.walk(root):
        for f in files:
            if f.endswith(".java") and f != "package-info.java":
                out.append(Path(dirpath) / f)
    return sorted(out)


def _scan_wrappers(repo: Path) -> Dict[str, List[str]]:
    """
    Map fully qualified org.uacalc class name -> list of wrapper simple class names
    that reference it via import.
    """
    root = repo / "java_wrapper" / "src"
    mapping: Dict[str, Set[str]] = defaultdict(set)
    if not root.is_dir():
        return {}
    for path in root.rglob("*Wrapper.java"):
        text = path.read_text(encoding="utf-8", errors="replace")
        imports = []
        for line in text.splitlines():
            m = _IMPORT_ORG_UACALC.match(line.strip())
            if m:
                imports.append(m.group(1))
        simple_wrapper = path.stem
        for fq in imports:
            mapping[fq].add(simple_wrapper)
    return {k: sorted(v) for k, v in sorted(mapping.items())}


def _python_org_packages(repo: Path) -> Set[str]:
    """Packages that have python/org/uacalc/<pkg>/__init__.py (nested 'a.b' -> path a/b)."""
    base = repo / "python" / "org" / "uacalc"
    if not base.is_dir():
        return set()
    found: Set[str] = set()

    def visit(dirpath: Path, pkg_suffix: List[str]) -> None:
        init = dirpath / "__init__.py"
        if init.is_file():
            found.add("org.uacalc." + ".".join(pkg_suffix) if pkg_suffix else "org.uacalc")
        for child in sorted(dirpath.iterdir()):
            if child.is_dir() and not child.name.startswith("_"):
                visit(child, pkg_suffix + [child.name])

    visit(base, [])
    return found


def _rust_submodules(repo: Path) -> Set[str]:
    """Names of uacalc_lib Python submodules from lib.rs (alg, io, ...)."""
    lib = repo / "uacalc_lib" / "src" / "lib.rs"
    if not lib.is_file():
        return set()
    txt = lib.read_text(encoding="utf-8", errors="replace")
    names: Set[str] = set()
    for line in txt.splitlines():
        line = line.strip()
        if line.startswith("pub mod "):
            m = re.match(r"pub mod (\w+);", line)
            if m:
                names.add(m.group(1))
    return names


def pkg_has_shim(package: str, py_pkgs: Set[str]) -> bool:
    if package in py_pkgs:
        return True
    pref = package + "."
    return any(p.startswith(pref) for p in py_pkgs)


def build_inventory(repo: Path) -> Dict[str, Any]:
    java_files = _walk_org_uacalc_java(repo)
    wrappers_by_fq = _scan_wrappers(repo)
    py_pkgs = _python_org_packages(repo)
    rust_modules = _rust_submodules(repo)

    # fqcn -> metadata
    classes: Dict[str, Any] = {}

    for jf in java_files:
        package, types, file_methods = _parse_java_file(jf)
        rel = jf.relative_to(repo).as_posix()
        if not types:
            fq = f"{package}.<file:{jf.name}>" if package else f"<file:{rel}>"
            classes[fq] = {
                "package": package or None,
                "source_relpath": rel,
                "kind": "file",
                "public_methods_file_guess": file_methods,
                "java_cli_wrappers": [],
                "python_org_package_hint": package if package and pkg_has_shim(package, py_pkgs) else None,
                "rust_uacalc_lib_submodule_hint": _map_java_package_to_rust_module(package),
            }
            continue

        for kind, name in types:
            fqcn = f"{package}.{name}"
            type_methods = file_methods  # file-level heuristic; finer would need a Java parser
            classes[fqcn] = {
                "package": package,
                "simple_name": name,
                "kind": kind,
                "source_relpath": rel,
                "public_methods_heuristic": type_methods,
                "java_cli_wrappers": wrappers_by_fq.get(fqcn, []),
                "python_org_shim_directory_exists": pkg_has_shim(package, py_pkgs),
                "rust_uacalc_lib_submodule_hint": _map_java_package_to_rust_module(package),
            }

    packages: Dict[str, Any] = defaultdict(lambda: {"classes": [], "java_sources": []})
    for fqcn, meta in classes.items():
        if "package" not in meta or not meta["package"]:
            continue
        pkg = meta["package"]
        packages[pkg]["classes"].append(fqcn)
        sr = meta.get("source_relpath")
        if sr and sr not in packages[pkg]["java_sources"]:
            packages[pkg]["java_sources"].append(sr)

    for pkg in packages:
        packages[pkg]["classes"] = sorted(packages[pkg]["classes"])
        packages[pkg]["java_sources"] = sorted(packages[pkg]["java_sources"])

    return {
        "meta": {
            "generated_at_utc": datetime.now(timezone.utc).isoformat(),
            "generator_version": GENERATOR_VERSION,
            "repo_root": repo.as_posix(),
            "java_org_uacalc_files_scanned": len(java_files),
            "java_org_uacalc_classes_and_units": len(classes),
            "rust_uacalc_lib_submodules": sorted(rust_modules),
            "python_org_uacalc_packages_with_init": sorted(py_pkgs),
        },
        "java_cli_wrapper_index": wrappers_by_fq,
        "packages": dict(sorted(packages.items())),
        "types": dict(sorted(classes.items())),
    }


def _map_java_package_to_rust_module(package: str) -> Optional[str]:
    if not package.startswith("org.uacalc."):
        return None
    rest = package[len("org.uacalc.") :]
    return rest.split(".", 1)[0]


def verify_fresh(repo: Path) -> int:
    inv = repo / "jython_comparison" / "parity_inventory.yaml"
    if not inv.is_file():
        print("parity_inventory.yaml missing; run generator", file=sys.stderr)
        return 2
    try:
        built = build_inventory(repo)
    except Exception as exc:  # pylint: disable=broad-exception-caught
        print(f"parity_inventory verify: failed to build inventory: {exc}", file=sys.stderr)
        return 1
    new_text = format_inventory_yaml(built, repo)
    try:
        existing_text = inv.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"parity_inventory.yaml: cannot read: {exc}", file=sys.stderr)
        return 1
    if _normalize_parity_inventory_text(new_text) != _normalize_parity_inventory_text(
        existing_text
    ):
        print(
            "parity_inventory.yaml differs from generator output; run: "
            "python jython_comparison/scripts/generate_parity_inventory.py",
            file=sys.stderr,
        )
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Exit non-zero if parity_inventory.yaml is missing or not reproducible.",
    )
    args = parser.parse_args()
    repo = _repo_root()
    if args.verify:
        return verify_fresh(repo)

    data = build_inventory(repo)
    out = repo / "jython_comparison" / "parity_inventory.yaml"
    write_yaml(out, data, repo)
    print(f"Wrote {out} ({data['meta']['java_org_uacalc_classes_and_units']} type/file units)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
