package scripts;

import org.uacalc.alg.Algebra;
import org.uacalc.alg.conlat.CongruenceLattice;
import org.uacalc.alg.conlat.Partition;
import org.uacalc.alg.op.Operation;
import org.uacalc.io.AlgebraIO;

/**
 * Java wrapper for UACalc functionality to enable comparison with Rust
 * implementation. Outputs results in JSON format.
 */
public class JavaWrapper {

    public static void main(String[] args) {
        if (args.length < 2) {
            System.err.println(
                    "Usage: JavaWrapper <operation> <ua_file> [args...]");
            System.err.println("Operations:");
            System.err.println(
                    "  properties <ua_file> - Print algebra properties");
            System.err.println(
                    "  cg <ua_file> <a> <b> - Print congruence generated by (a,b)");
            System.err.println(
                    "  lattice <ua_file> - Print congruence lattice properties");
            System.exit(1);
        }

        String operation = args[0];
        String uaFile = args[1];

        try {
            switch (operation) {
                case "properties":
                    outputProperties(uaFile);
                    break;
                case "cg":
                    if (args.length < 4) {
                        System.err.println(
                                "Usage: JavaWrapper cg <ua_file> <a> <b>");
                        System.exit(1);
                    }
                    int a = Integer.parseInt(args[2]);
                    int b = Integer.parseInt(args[3]);
                    outputCg(uaFile, a, b);
                    break;
                case "lattice":
                    outputLattice(uaFile);
                    break;
                default:
                    System.err.println("Unknown operation: " + operation);
                    System.exit(1);
            }
        }
        catch (Exception e) {
            System.out.println("{\"error\":\""
                    + e.getMessage().replace("\"", "\\\"") + "\",\"type\":\""
                    + e.getClass().getSimpleName() + "\"}");
            System.exit(1);
        }
    }

    private static void outputProperties(String uaFile) throws Exception {
        long startMemory = getMemoryUsage();

        Algebra algebra = AlgebraIO.readAlgebra(uaFile);

        long endMemory = getMemoryUsage();

        StringBuilder result = new StringBuilder();
        result.append("{");
        result.append("\"name\":\"").append(algebra.getName()).append("\",");
        result.append("\"cardinality\":").append(algebra.cardinality())
                .append(",");
        result.append("\"operation_count\":")
                .append(algebra.operations().size()).append(",");
        result.append("\"java_memory_mb\":")
                .append((endMemory - startMemory) / 1024.0 / 1024.0)
                .append(",");

        // Operation symbols
        result.append("\"operation_symbols\":[");
        boolean first = true;
        for (Operation op : algebra.operations()) {
            if (!first) {
                result.append(",");
            }
            result.append("\"").append(op.symbol().toString()).append("\"");
            first = false;
        }
        result.append("],");

        // Operation arities
        result.append("\"operation_arities\":[");
        first = true;
        for (Operation op : algebra.operations()) {
            if (!first) {
                result.append(",");
            }
            result.append(op.arity());
            first = false;
        }
        result.append("]");
        result.append("}");

        System.out.println(result.toString());
    }

    private static void outputCg(String uaFile, int a, int b) throws Exception {
        long startMemory = getMemoryUsage();

        Algebra algebra = AlgebraIO.readAlgebra(uaFile);

        // Cast to SmallAlgebra since CongruenceLattice requires it
        org.uacalc.alg.SmallAlgebra smallAlgebra = (org.uacalc.alg.SmallAlgebra) algebra;
        CongruenceLattice conLat = new CongruenceLattice(smallAlgebra);

        Partition cg = conLat.Cg(a, b);

        long endMemory = getMemoryUsage();

        StringBuilder result = new StringBuilder();
        result.append("{");
        result.append("\"java_memory_mb\":")
                .append((endMemory - startMemory) / 1024.0 / 1024.0)
                .append(",");

        // Convert partition to list of blocks
        result.append("\"partition\":[");
        int[][] blocks = cg.getBlocks();
        for (int i = 0; i < blocks.length; i++) {
            if (i > 0) result.append(",");
            result.append("[");
            boolean first = true;
            for (int element : blocks[i]) {
                if (!first) result.append(",");
                result.append(element);
                first = false;
            }
            result.append("]");
        }
        result.append("]");
        result.append("}");

        System.out.println(result.toString());
    }

    private static void outputLattice(String uaFile) throws Exception {
        long startMemory = getMemoryUsage();

        Algebra algebra = AlgebraIO.readAlgebra(uaFile);

        // Cast to SmallAlgebra since CongruenceLattice requires it
        org.uacalc.alg.SmallAlgebra smallAlgebra = (org.uacalc.alg.SmallAlgebra) algebra;
        CongruenceLattice conLat = new CongruenceLattice(smallAlgebra);

        long endMemory = getMemoryUsage();

        StringBuilder result = new StringBuilder();
        result.append("{");
        result.append("\"size\":").append(conLat.cardinality()).append(",");
        result.append("\"join_irreducibles\":")
                .append(conLat.joinIrreducibles().size()).append(",");
        result.append("\"height\":").append(conLat.joinIrreducibles().size())
                .append(","); // Using join irreducibles as height approximation
        result.append("\"width\":").append(conLat.cardinality()).append(","); // Using
                                                                              // cardinality
                                                                              // as
                                                                              // width
                                                                              // approximation
        result.append("\"java_memory_mb\":")
                .append((endMemory - startMemory) / 1024.0 / 1024.0);
        result.append("}");

        System.out.println(result.toString());
    }

    private static long getMemoryUsage() {
        Runtime runtime = Runtime.getRuntime();
        return runtime.totalMemory() - runtime.freeMemory();
    }
}
